markdown: redcarpet
highlighter: pygments
pygments_options: ['cssclass']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data","tables","prettify"] 
  
